// Shared event data for marketplace and event detail pages
export const marketplaceEvents = [
  {
    id: 1,
    title: 'ALAS TRAIL RUN 2026',
    organizer: 'Mojokerto Extreme',
    category: 'Festival',
    location: 'Pacet, Mojokerto',
    date: 'Aug 15, 2026',
    network: 'Ethereum',
    cryptoPrice: '0.005 ETH',
    fiatPrice: 'Rp 250.000',
    status: 'Live Minting',
    statusColor: 'neon',
    supply: { minted: 85, total: 150 },
    rarity: 'VIP Pass',
    action: 'Mint Now',
    bg: 'linear-gradient(135deg, #0a2010 0%, #0f3d2e 100%)',
    trending: true,
    // Detail data for event page
    description: 'Trail run menantang di kaki Gunung Arjuno dengan pemandangan savana Alas Purwo.',
    tiers: [
      { id: 1, name: 'REGULAR', price: '0.001 ETH', fiat: 'Rp 50.000', network: 'Ethereum', benefits: ['Akses Masuk Area Umum', 'Standard Digital Ticket NFT'], accent: 'cyan', glow: 'shadow.cyan.500/30', border: 'border.cyan.500/50', badgeBg: 'bg.cyan.500/20', badgeText: 'text.cyan.400' },
      { id: 2, name: 'VIP', price: '0.003 ETH', fiat: 'Rp 150.000', network: 'Ethereum', benefits: ['Akses Masuk Utama Event', 'Digital POAP Finisher Badge', 'Free Merchandise NFT'], accent: 'emerald', glow: 'shadow.emerald.500/30', border: 'border.emerald.500/50', badgeBg: 'bg.emerald.500/20', badgeText: 'text.emerald.400' },
      { id: 3, name: 'VVIP', price: '0.01 ETH', fiat: 'Rp 500.000', network: 'Ethereum', benefits: ['Akses Backstage Eksklusif', 'Free Merchandise NFT & Fisik', 'Drink Coupon & VIP Lounge', 'Front Row Seat'], accent: 'amber', glow: 'shadow.amber.500/30', border: 'border.amber.500/50', badgeBg: 'bg.amber.500/20', badgeText: 'text.amber.400' },
    ],
  },
  {
    id: 2,
    title: 'TALUS WEB3 SUMMIT',
    organizer: 'Talus Network',
    category: 'Konferensi',
    location: 'Jakarta, Indonesia',
    date: 'Sep 22, 2026',
    network: 'Base',
    cryptoPrice: '0.002 ETH',
    fiatPrice: 'Rp 100.000',
    status: 'Live Minting',
    statusColor: 'neon',
    supply: { minted: 420, total: 500 },
    rarity: 'Tier 1',
    action: 'Mint Now',
    bg: 'linear-gradient(135deg, #0d1f2d 0%, #1a2030 100%)',
    trending: true,
    description: 'Konferensi Web3 terbesar di Asia Tenggara dengan speaker global dari Talus Network.',
    tiers: [
      { id: 1, name: 'REGULAR', price: '0.002 ETH', fiat: 'Rp 100.000', network: 'Base', benefits: ['Akses Semua Sesi Talk', 'Digital Certificate NFT'], accent: 'cyan', glow: 'shadow.cyan.500/30', border: 'border.cyan.500/50', badgeBg: 'bg.cyan.500/20', badgeText: 'text.cyan.400' },
      { id: 2, name: 'VIP', price: '0.005 ETH', fiat: 'Rp 250.000', network: 'Base', benefits: ['Akses VIP Lounge', 'Meet & Greet Speaker', 'Exclusive Merch NFT'], accent: 'emerald', glow: 'shadow.emerald.500/30', border: 'border.emerald.500/50', badgeBg: 'bg.emerald.500/20', badgeText: 'text.emerald.400' },
      { id: 3, name: 'VVIP', price: '0.02 ETH', fiat: 'Rp 1.000.000', network: 'Base', benefits: ['Private Dinner with Founders', 'Investor Access Pass', 'Lifetime Talus Ecosystem Access'], accent: 'amber', glow: 'shadow.amber.500/30', border: 'border.amber.500/50', badgeBg: 'bg.amber.500/20', badgeText: 'text.amber.400' },
    ],
  },
  {
    id: 3,
    title: 'ANIME MATSURI: SOUL SOCIETY',
    organizer: 'OtakuVerse',
    category: 'Exhibition',
    location: 'Surabaya, East Java',
    date: 'Oct 10, 2026',
    network: 'Polygon',
    cryptoPrice: '50 MATIC',
    fiatPrice: 'Rp 250.000',
    status: 'Selling Fast',
    statusColor: 'neon3',
    supply: { minted: 890, total: 1000 },
    rarity: 'General Admission',
    action: 'Buy on Secondary',
    bg: 'linear-gradient(135deg, #2d0f1a 0%, #1a0f2e 100%)',
    trending: false,
    description: 'Pameran anime & budaya pop Jepang terbesar di Jawa Timur.',
    tiers: [
      { id: 1, name: 'REGULAR', price: '50 MATIC', fiat: 'Rp 250.000', network: 'Polygon', benefits: ['Akses Pameran Utama', 'Goodie Bag Digital'], accent: 'cyan', glow: 'shadow.cyan.500/30', border: 'border.cyan.500/50', badgeBg: 'bg.cyan.500/20', badgeText: 'text.cyan.400' },
      { id: 2, name: 'VIP', price: '120 MATIC', fiat: 'Rp 600.000', network: 'Polygon', benefits: ['Early Entry', 'Exclusive Figure NFT', 'Artist Meet & Greet'], accent: 'emerald', glow: 'shadow.emerald.500/30', border: 'border.emerald.500/50', badgeBg: 'bg.emerald.500/20', badgeText: 'text.emerald.400' },
      { id: 3, name: 'VVIP', price: '300 MATIC', fiat: 'Rp 1.500.000', network: 'Polygon', benefits: ['Private Tour with Curator', 'Signed Artwork NFT', 'VIP After Party Access'], accent: 'amber', glow: 'shadow.amber.500/30', border: 'border.amber.500/50', badgeBg: 'bg.amber.500/20', badgeText: 'text.amber.400' },
    ],
  },
  {
    id: 4,
    title: 'RINJANI EXPEDITION VIP',
    organizer: 'Trekker DAO',
    category: 'Festival',
    location: 'Lombok, NTB',
    date: 'Nov 01, 2026',
    network: 'Ethereum',
    cryptoPrice: '0.01 ETH',
    fiatPrice: 'Rp 500.000',
    status: 'Upcoming',
    statusColor: 'neon2',
    supply: { minted: 0, total: 50 },
    rarity: 'Legendary',
    action: 'Join Whitelist',
    bg: 'linear-gradient(135deg, #1f1c0d 0%, #302b1a 100%)',
    trending: true,
    description: 'Ekspedisi mendaki Gunung Rinjani 3 hari 2 malam dengan pemandu profesional.',
    tiers: [
      { id: 1, name: 'REGULAR', price: '0.005 ETH', fiat: 'Rp 250.000', network: 'Ethereum', benefits: ['Pemandu Bergizi', 'Tenda & Makan', 'Sertifikat Pendakian NFT'], accent: 'cyan', glow: 'shadow.cyan.500/30', border: 'border.cyan.500/50', badgeBg: 'bg.cyan.500/20', badgeText: 'text.cyan.400' },
      { id: 2, name: 'VIP', price: '0.01 ETH', fiat: 'Rp 500.000', network: 'Ethereum', benefits: ['Private Guide 1:1', 'Gourmet Meals', 'Portable Oxygen', 'Summit Photo NFT'], accent: 'emerald', glow: 'shadow.emerald.500/30', border: 'border.emerald.500/50', badgeBg: 'bg.emerald.500/20', badgeText: 'text.emerald.400' },
      { id: 3, name: 'VVIP', price: '0.03 ETH', fiat: 'Rp 1.500.000', network: 'Ethereum', benefits: ['Helicopter Transfer', 'Luxury Glamping', 'Personal Sherpa', 'Lifetime Trekker DAO Membership'], accent: 'amber', glow: 'shadow.amber.500/30', border: 'border.amber.500/50', badgeBg: 'bg.amber.500/20', badgeText: 'text.amber.400' },
    ],
  },
  {
    id: 5,
    title: 'NEON CITY RAVE VOL. 4',
    organizer: 'Electronic Horizon',
    category: 'Konser',
    location: 'Bali, Indonesia',
    date: 'Dec 31, 2026',
    network: 'Polygon',
    cryptoPrice: '120 MATIC',
    fiatPrice: 'Rp 1.500.000',
    status: 'Sold Out',
    statusColor: 'muted',
    supply: { minted: 2000, total: 2000 },
    rarity: 'Tier 2',
    action: 'Buy on Secondary',
    bg: 'linear-gradient(135deg, #1a0d2d 0%, #2d1a30 100%)',
    trending: false,
    description: 'Pesta malam tahun baru electronic music terbesar di Bali.',
    tiers: [
      { id: 1, name: 'REGULAR', price: '60 MATIC', fiat: 'Rp 750.000', network: 'Polygon', benefits: ['General Admission', '1 Drink Token'], accent: 'cyan', glow: 'shadow.cyan.500/30', border: 'border.cyan.500/50', badgeBg: 'bg.cyan.500/20', badgeText: 'text.cyan.400' },
      { id: 2, name: 'VIP', price: '120 MATIC', fiat: 'Rp 1.500.000', network: 'Polygon', benefits: ['VIP Area Access', '3 Drink Tokens', 'Fast Lane Entry'], accent: 'emerald', glow: 'shadow.emerald.500/30', border: 'border.emerald.500/50', badgeBg: 'bg.emerald.500/20', badgeText: 'text.emerald.400' },
      { id: 3, name: 'VVIP', price: '300 MATIC', fiat: 'Rp 3.750.000', network: 'Polygon', benefits: ['Stage Side Access', 'Artist Meet & Greet', 'Bottle Service', 'After Party Access'], accent: 'amber', glow: 'shadow.amber.500/30', border: 'border.amber.500/50', badgeBg: 'bg.amber.500/20', badgeText: 'text.amber.400' },
    ],
  },
  {
    id: 6,
    title: 'BLOCKPASS ESPORTS ARENA',
    organizer: 'Gaming Guild',
    category: 'Esports',
    location: 'Jakarta, Indonesia',
    date: 'Aug 28, 2026',
    network: 'Base',
    cryptoPrice: '0.001 ETH',
    fiatPrice: 'Rp 50.000',
    status: 'Live Minting',
    statusColor: 'neon',
    supply: { minted: 150, total: 1000 },
    rarity: 'General Admission',
    action: 'Mint Now',
    bg: 'linear-gradient(135deg, #0d2d2d 0%, #1a3030 100%)',
    trending: false,
    description: 'Turnamen esports Web3 dengan hadiah total $50,000.',
    tiers: [
      { id: 1, name: 'REGULAR', price: '0.001 ETH', fiat: 'Rp 50.000', network: 'Base', benefits: ['Spectator Access', 'Digital Trophy NFT'], accent: 'cyan', glow: 'shadow.cyan.500/30', border: 'border.cyan.500/50', badgeBg: 'bg.cyan.500/20', badgeText: 'text.cyan.400' },
      { id: 2, name: 'VIP', price: '0.003 ETH', fiat: 'Rp 150.000', network: 'Base', benefits: ['Player Meet & Greet', 'Exclusive Skin NFT', 'Backstage Access'], accent: 'emerald', glow: 'shadow.emerald.500/30', border: 'border.emerald.500/50', badgeBg: 'bg.emerald.500/20', badgeText: 'text.emerald.400' },
      { id: 3, name: 'VVIP', price: '0.01 ETH', fiat: 'Rp 500.000', network: 'Base', benefits: ['Coaching Session with Pro', 'Signed Merch', 'Tournament Partner Access'], accent: 'amber', glow: 'shadow.amber.500/30', border: 'border.amber.500/50', badgeBg: 'bg.amber.500/20', badgeText: 'text.amber.400' },
    ],
  },
];

// Helper function to get event by ID
export function getEventById(id: number) {
  return marketplaceEvents.find((event) => event.id === id) || marketplaceEvents[0];
}